### ISSUE TITLE
Version 0.6.2?

### ISSUE THREAD

**Issue by jagthedrummer** [contribsys/faktory_worker_ruby#13]
Hey Mike, was just hoping you might cut a new version of this gem. In order to land an ActiveJob adapter other folks will need to be able to get at the testing extensions and the fix you made here: https://github.com/contribsys/faktory_worker_ruby/commit/ad454bb4f72506025dbdde74206e40cddb886fc3

**Comment by mperham** [comment]
Will do this weekend. Thanks for the reminder.

**Comment by mperham** [comment]
0.7.0 has been released, to better correspond with Faktory 0.7.0.
