### ISSUE TITLE
Can't push job

### ISSUE THREAD

**Issue by apa512** [contribsys/faktory_worker_ruby#16]
I can't seem to push jobs using the latest server and Ruby client. Am I missing something basic?

```ruby
class MyJob
  include Faktory::Job

  def perform(a)
    # empty because I only want to push the job, not consume it, with Ruby
  end
end
```

```ruby
MyJob.perform_async(1)
```

```
Faktory::CommandError: MALFORMED json: cannot unmarshal object into Go struct field Job.jobtype of type string
from /usr/local/bundle/gems/faktory_worker_ruby-0.7.0/lib/faktory/client.rb:220:in `result'
```

**Comment by apa512** [comment]
Works with `Client#push`, but only if the jobtype argument is a string. Maybe I have some weird JSON gem installed that interferes with Faktory?

**Comment by mperham** [comment]
No one else has reported a problem; not sure what's going wrong here.

**Comment by apa512** [comment]
```ruby
JSON.dump({ jobtype: MyJob })
=>
'{"jobtype": {}}'
```
This is obviously non-standard behavior but perhaps it's still a good idea to call `to_s` on jobtype in `Client#push`.

**Comment by mperham** [comment]
```ruby
    def push(job)
      transaction do
        command "PUSH", JSON.generate(job)
        ok!
        job["jid"]
      end
    end
```

It's like that so it doesn't special-case any particular keys.  Definitely something non-standard in your app config.  As my blog said a few years ago:

> So many gems declare a dependency on json, oj, multi_json, or yajl-ruby. There's so many ossified layers of cruft around JSON processing that only one course of action makes sense: remove it all. JSON has been in the stdlib since 1.9, you don't need to declare any dependencies at all. Just `require 'json'` and let Ruby deal with it.

Let me know if you figure it out.

**Comment by apa512** [comment]
I dealt with it by using `Client#push` directly. This works fine for me since I don't do any processing in Ruby and didn't want to use PascalCase queue names anyway.
