### ISSUE TITLE
Should we remove blockless_inline_is_a_bad_idea_but_I_wanna_do_it_anyway?

### ISSUE THREAD

**Issue by jagthedrummer** [contribsys/faktory_worker_ruby#18]
The `blockless_inline_is_a_bad_idea_but_I_wanna_do_it_anyway!` method for testing was added when it looked like we'd need it to be able to get an ActiveJob adapter to pass the Rails test suite. Since the adapter now lives in this gem I'm not sure there's a compelling reason to keep that method around. Just thought I'd get a sanity check on that before submitting a PR.

**Comment by mperham** [comment]
Fine with me.
