### ISSUE TITLE
Add Daemon config to CLI

### ISSUE THREAD

**Issue by nvh0412** [contribsys/faktory_worker_ruby#21]
As a developer, I want to run my faktory_worker under a daemon worker and write log to a logfile

https://github.com/contribsys/faktory_worker_ruby/blob/master/lib/faktory/cli.rb#L31-L33

Based on what I have learned from sidekiq cli, we can bring all daemon stuff to it, right? I have tried adding daemon config to our gem and it's working in my end, so I'm gonna create an issue there and if you allow me to create a PR to add this one, please let me know

**Comment by mperham** [comment]
Why aren’t you using systemd?

**Comment by nvh0412** [comment]
Haven't thought about it yet. Thanks. But `daemon config` is still an easy step to run and catch up for a newbie

**Comment by mperham** [comment]
Modern Linux distros use systemd to start and monitor system services, handle logging, etc.  Daemonization hasn't been recommended for over a decade now.
