### ISSUE TITLE
Bug without custom parameters

### ISSUE THREAD

**Issue by wishdev** [contribsys/faktory_worker_ruby#29]
https://github.com/contribsys/faktory_worker_ruby/blob/369911c6b313a6f38e0d04a2a25855cbef38c033/lib/faktory/logging.rb#L32

This fails unless there is a 'custom' key in the hash. #dig would be the current obvious choice here - but that is Ruby 2.3 and higher.

Since you support 2.2.2 and higher maybe the easiest option is to just pull this  https://github.com/marcandre/backports/blob/master/lib/backports/2.3.0/hash/dig.rb in from backports until you push up to 2.3 where it could go away. It's all of 10 lines so it's not a huge push. Obviously adding backports as a requirement would work as well but might be a little heavier lift.

**Comment by mperham** [comment]
Good catch. We need better test coverage obviously. I’m fine with using dig and bumping our requirement to 2.3.

**Comment by mperham** [comment]
0.8.1 has been released with this fix.  Thank you for reporting it!
