### ISSUE TITLE
Errno::ECONNRESET: Connection reset by peer - No response

### ISSUE THREAD

**Issue by jagthedrummer** [contribsys/faktory_worker_ruby#3]
I'm trying to get going with this and am running into a weird error.

First I installed the faktory server via homebrew.

Then I start `faktory` locally:

```
$ faktory
Faktory 0.5.0
Copyright © 2017 Contributed Systems LLC
Licensed under the GNU Public License 3.0
INFO[2017-11-08T22:20:41.828681916-06:00] Initializing storage at /Users/jgreen/.faktory/db 
INFO[2017-11-08T22:20:41.850672271-06:00] Now listening at localhost:7419, press Ctrl-C to stop 
INFO[2017-11-08T22:20:41.850750997-06:00] Web server now listening on port 7420  
```

Then I installed this gem in my `Gemfile`

```
gem 'faktory_worker_ruby', git: 'https://github.com/contribsys/faktory_worker_ruby'
```

Then in `app/jobs/my_job.rb` I have this code:

```ruby
require 'faktory'

class MyJob
  include Faktory::Job

  def perform(some_id)
    puts "we should do something with this id : #{some_id}"
  end
end
```

Then I open a Rails console and do:

```
> MyJob.perform_async(42)
Errno::ECONNRESET: Connection reset by peer - No response
	from (irb):4
```

The server console shows this when the error happens:

```
ERRO[2017-11-08T22:20:53.102064455-06:00] Invalid client data in AHOYInvalid client Wid
```

**Comment by mperham** [comment]
Ah right, I need to publish 0.6.0 of the rubygem and homebrew faktory recipe.  0.6.0 was released today but only the docker image was published.

**Comment by mperham** [comment]
Ok, rubygem and homebrew recipe updated.  You'll have better luck if you reinstall the server and gem.

**Comment by jagthedrummer** [comment]
Yay! That did it. Thanks, @mperham.
