### ISSUE TITLE
What connection string do I need when running Rails inside a docker container?

### ISSUE THREAD

**Issue by bo-oz** [contribsys/faktory_worker_ruby#33]
The call to localhost:7419 results in an error:

`Errno::ECONNREFUSED in StaticsController#home
Connection refused - connect(2) for "localhost" port 7419`

I guess I need different setting for FAKTORY_URL, but I have tried a ton of different options. Any ideas?

**Comment by bo-oz** [comment]
eventuallly found the solution. Anyone looking for this, check this GIT for setting up your docker-compose file: https://gist.github.com/bo-oz/ab509873294e61ae422c2814419fc46f

**Comment by mperham** [comment]
Good detective work, I'm glad you tracked it down.  I believe docker-compose is considered best practice for linking a bunch of services in Docker containers together by mapping all the various ports into the necessary containers.
