### ISSUE TITLE
Worker only checking default channel?

### ISSUE THREAD

**Issue by puddl3glum** [contribsys/faktory_worker_ruby#37]
I have a worker defined in a file `workers.rb`:
```
class ChannelWorker
  include Faktory::Job

  faktory_options queue: 'channels', queues:['channels'], retry: 25, backtrace: 0

  def perform(username)
  ...
  end
end
```

I am trying to get this worker to pull work from the `channels` queue. While `ChannelWorker.perform_async channel` puts work into the `channels` queue, when running the worker,  it does not get the work from the queue.

When removing the `faktory_options` line, the worker runs like normal, but only on the default queue, which I am trying to avoid so that I can have a queue per job type.

I checked the options that the worker currently has with `ChannelWorker.get_faktory_options`, which returns `{"retry"=>25, "queue"=>"channels", "queues"=>["channels"], "backtrace"=>0}`, leading me to believe that it _should_ be pulling from the queue.

**Comment by jagthedrummer** [comment]
I think you need to tell `faktory-worker` what queues to work on with something like:

```
bundle exec faktory-worker -q channels
```

**Comment by puddl3glum** [comment]
Oh wow, thank you. I couldn't find this in the docs anywhere.
