### ISSUE TITLE
Faktory::CommandError: ERR Invalid password

### ISSUE THREAD

**Issue by jagthedrummer** [contribsys/faktory_worker_ruby#4]
I'm trying to connect to a local faktory instance with a password and am not having any luck.

I started the server like this:

```
$ FAKTORY_PASSWORD=test faktory
```

Then if I try to connect _without_ configuring anything I see this, as expected:

```
> MyJob.perform_async(42)
ArgumentError: Server requires password, but none has been configured
```

So then I set ENV vars like this:

```
FAKTORY_PROVIDER=MY_FAKTORY_URL
MY_FAKTORY_URL=tcp://:test@localhost:7419
```

And then when I try to connect I see this:

```
> MyJob.perform_async(42)
Faktory::CommandError: ERR Invalid password
```

Am I missing something about how to configure the ruby client with a password?

**Comment by mperham** [comment]
Nice catch, I've verified that the server is hashing incorrectly; this will be fixed in the next release.  The Ruby code is correct.

**Comment by mperham** [comment]
Of course, all my testing was with the Go client, which used the same incorrect algorithm so it passed.  Doh. :-/

**Comment by jagthedrummer** [comment]
Excellent. I'll be watching out for the next release.

**Comment by mperham** [comment]
Another user pointed out that the Go was right and Ruby was wrong.  You should be able to use fwr/master and get it to work against 0.6.0 now.

**Comment by jagthedrummer** [comment]
Yep, it's working as expected now. Thanks, @mperham!
