### ISSUE TITLE
getting Error: "unknown: No jobtype registered: RunnerWorker"

### ISSUE THREAD

**Issue by joshdvir** [contribsys/faktory_worker_ruby#40]
Hi,

I have an inconsistent issue with the ruby worker.

When calling specific worker sometimes I get the error "unknown: No jobtype registered: RunnerWorker" 

The worker doesn't recognize the "RunnerWorker".

"RunnerWorker" is the only worker in the system and I start faktory-worker like this: "bundle exec faktory-worker --require ./workers/runner_worker.rb --queue runner-manager,1 --environment production"

Your help is appreciated

Josh.

**Comment by mperham** [comment]
The word "registered" does not exist in fwr master or faktory master.  I have no idea where this error message is coming from. Are you running another type of worker?

**Comment by joshdvir** [comment]
@mperham thank you, you are right we were listening on the same queue with another worker a nodejs one.
