### ISSUE TITLE
Queue Size

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory_worker_ruby#43]
Is there a way to fetch the current queue size? 

We use a method in sidekiq to fetch the "least busy" queue from a subset of queues.

**Comment by mperham** [comment]
Faktory doesn't have a comprehensive API like Sidekiq does today.  A possible future feature is a command proxy that allows you to send commands to the underlying Redis, so we could provide access for building data APIs like that.

**Comment by scottrobertson** [comment]
No problem :) will just pick random queues for now. Thanks!
