### ISSUE TITLE
undefined method `jobs' for nil:NilClass

### ISSUE THREAD

**Issue by scottrobertson** [contribsys/faktory_worker_ruby#44]
Hey

Having an issue with batches on a few specific workers.

We have a batch, which enqueues jobs, and then those jobs can add to the batch. This has been working totally fine, but for some reason occasionally this happens.

```
undefined method `jobs' for nil:NilClass
```

That line is `batch.jobs do`

However, as you can see, there is a bid set. (it's in custom, is that right? We don't set that manually).

<img width="822" alt="Screenshot 2020-01-20 at 15 39 44" src="https://user-images.githubusercontent.com/68361/72739207-1e260800-3b9b-11ea-8b72-ca7acf257c6d.png">

**Comment by scottrobertson** [comment]
Ok, i have added some logging to this.

If i dump the job JSON, there is:

```
"custom" => {"bid" => "b-cFUpJhAhg49s1w"}
```

However, within the job `bid` is nil.

Will do some more debugging.

**Comment by scottrobertson** [comment]
Ok, added some more logging in the `batch` method in the lib. 

```
puts self.instance_variables
=> @jid
```

**Comment by scottrobertson** [comment]
Got it

**Comment by mperham** [comment]
See faktory/middleware/batch and faktory/job#batch

**Comment by scottrobertson** [comment]
@mperham PR already sent. bid was not being set on the job object at all.

**Comment by scottrobertson** [comment]
@mperham PR closed, let's continue the discussion here. From what i can see, that middlewhere `configure_worker` is just not being called at all.

**Comment by mperham** [comment]
require 'faktory' was called before Faktory::CLI was defined so Faktory.worker? returned false.

**Comment by scottrobertson** [comment]
Thanks @mperham
