### ISSUE TITLE
How to determine that worker process is alive and working?

### ISSUE THREAD

**Issue by Envek** [contribsys/faktory_worker_ruby#47]
Is there any way to check each worker process for its _health_? To be able to restart them in case if they will get stuck or freeze or anything else.

If worker isn't busy and isn't _able_ to take new jobs, I want to kill it and restart.

It is primarily needed for deploying to Kubernetes as it is considered a best practice to always include liveness checks for containers in k8s pods. For example it may be any executable (e.g. shell script) that will return 0 if worker is healthy and something else if it is not. Also checks may be TCP or HTTP probes but I don't think that they fit for worker processes case.

Thank you for faktory!

**Comment by scottrobertson** [comment]
Have you experienced workers getting stuck, or unable to accept jobs? We are processing ~10m jobs per day, and this is not something we have seen.

**Comment by Envek** [comment]
We're not in production yet, so no, have not experienced… yet :smile:

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Related-Projects#kubernetes

**Comment by Envek** [comment]
Ok, will look on how to re-implement [sidekiq_alive](https://github.com/arturictus/sidekiq_alive) for faktory.

Thank you!

**Comment by mperham** [comment]
Oh, sorry I didn’t notice this was FWR and not Sidekiq. Yep, the same principle applies. If you find it relatively easy and send me a PR we could probably bake this into the core gem as Docker and k8s seem to be more and more popular.
