### ISSUE TITLE
Add -L option output the log

### ISSUE THREAD

**Issue by gigantik** [contribsys/faktory_worker_ruby#53]
This is an issue when you're running the faktory-worker in a service cause you need the logs to live somewhere similar to Sidekiq.

Propsal:

```
bundle exec faktory-worker -L log/faktory.log
```

**Comment by mperham** [comment]
Nope. Modern daemons log to stdout and let the OS manage the log output location, rotation, etc. Logfiles are legacy.

**Comment by mperham** [comment]
https://www.freedesktop.org/software/systemd/man/daemon.html#New-Style%20Daemons

**Comment by gigantik** [comment]
Right now I'm running Faktory on Upstart

```
      description "Elastic Beanstalk Faktory Upstart Manager"

      start on runlevel [2345]
      stop on runlevel [!2345]

      respawn

      script
      exec /bin/bash <<"EOF"
        EB_SCRIPT_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k script_dir)
        EB_SUPPORT_DIR=$(/opt/elasticbeanstalk/bin/get-config container -k support_dir)

        . $EB_SUPPORT_DIR/envvars-wrapper.sh
        . $EB_SCRIPT_DIR/use-app-ruby.sh

        cd $EB_APP_STAGING_DIR
        exec su -s /bin/bash -c "bundle exec faktory-worker" webapp
      EOF
      end script
```

**Comment by gigantik** [comment]
How I supposed to output the log from do you have any clues? I tried `console log`.

**Comment by mperham** [comment]
Upstart has been deprecated for 7+ years now, Ubuntu moved to systemd in 15.04. Can you use any other deployment platform or a more modern Linux?

If you have a service `/etc/init/faktory-worker.service`, Upstart will put its output in `/var/log/upstart/faktory-worker.log`.
