### ISSUE TITLE
Unable to process jobs outside of ActiveJob

### ISSUE THREAD

**Issue by robinvdvleuten** [contribsys/faktory_worker_ruby#57]
We're using Faktory in a setup where Rails handles the API and a couple of backend processes are written in Go. These backend processes are receiving their work through a Faktory instance. 

In Rails we are pushing new jobs by utilizing (or misusing?) the ActiveJob classes. This allows us to have custom Faktory configuration per job (like queue name etc). But the Faktory adapter for ActiveJob wraps the name of the job before sending it to Faktory (_ActiveJob::QueueAdapters::FaktoryAdapter::JobWrapper_) so in Go we cannot register the correct handler for it. So currently we have a middleware "unwrapping" the name of the job;

```rb
class Faktory::Middleware::Unwrap
  class Client
    def call(payload, _pool)
      wrapped_job_klass = payload.dig('custom', 'wrapped')
      if wrapped_job_klass
        payload['jobtype'] = wrapped_job_klass
        payload['custom'] = payload['custom'].except('wrapped')
      end
      yield
    end
  end
end
```

I can imagine that more developers will run into this and it does not feel right with Faktory's strength to be a polyglot job processing framework. Thus it would be great to be able to configure the "wrapping" on Faktory itself instead of depending on custom middleware.

**Comment by mperham** [comment]
Do not use ActiveJob, it is designed for use within Rails only.  Use the
Faktory::Job API.

**Comment by robinvdvleuten** [comment]
Indeed if we do use the `include Faktory::Job` and the `perform_async` method, it works as expected.

**Comment by manuelvanrijn** [comment]
I've added a reference in the wiki page regarding this scenario.
