### ISSUE TITLE
Add support for testing configuration

### ISSUE THREAD

**Issue by thebadmonkeydev** [contribsys/faktory_worker_ruby#6]
It would be nice to be able to fake queueing jobs for testing like [sidekiq does](https://github.com/mperham/sidekiq/wiki/Testing).  I'm not sure the correct way to go about adding something like that but I'll certainly take a crack at it if no one else wants to.

**Comment by thebadmonkeydev** [comment]
I have a very naive implementation of faking tests over on my fork.

https://github.com/contribsys/faktory_worker_ruby/compare/master...thebadmonkeydev:add-testing-support

Must admit, it's pretty much pulled exactly from Sidekiq's testing module, but I figured that'd be a good place to start.  I'll try to get inlining on that branch before submitting a PR.  But for now, that change handles my use case at least.

**Comment by mperham** [comment]
Looks like a good start.  Can you open a PR?

**Comment by mperham** [comment]
One thing I will probably ask is to remove blockless inline!, see here for discussion.  We could still allow it in the development environment for people who want to run jobs without Faktory installed locally.

https://github.com/mperham/sidekiq/issues/3495

**Comment by prsimp** [comment]
Looks like this was closed by https://github.com/contribsys/faktory_worker_ruby/pull/7 -- or was there some more work that wasn't captured in that PR?
