### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by arjun810** [contribsys/faktory_worker_ruby#73]
Hey there, any chance of getting a new release? Took me a while to figure out why Client.push wasn't working without a job id, since the code on GitHub clearly filled it in

**Comment by mperham** [comment]
Yes, I will release tomorrow. Thanks for the reminder and sorry for the trouble.

**Comment by arjun810** [comment]
No worries and thank you!

**Comment by mperham** [comment]
1.2.0 is now available.
