### ISSUE TITLE
New Relic instrumentation?

### ISSUE THREAD

**Issue by Deekor** [contribsys/faktory_worker_ruby#81]
Looks like new relic [auto detects sidekiq workers](https://docs.newrelic.com/docs/apm/agents/ruby-agent/background-jobs/sidekiq-instrumentation/) but im not seeing any way to instrument a faktory worker, is there any known way to accomplish this?

**Comment by mperham** [comment]
Seems like this is a better question for New Relic. I don’t know anything about their APIs or usage but I’d be happy to provide advice or change FWR to make this as easy as possible.

**Comment by Deekor** [comment]
Ya, figured I'd ask the community here to check if its been done, before I dive into trying to request a feature from them.

**Comment by Deekor** [comment]
Turns out this is as easy as 

```
class MyWorker
  include Faktory::Job
  include ::NewRelic::Agent::Instrumentation::ControllerInstrumentation # include new relic 
  
  def perform
   ...
  end

  add_transaction_tracer :perform, category: :task # trace the perform method
end
```
