### ISSUE TITLE
Pool increase in a release?

### ISSUE THREAD

**Issue by Deekor** [contribsys/faktory_worker_ruby#82]
Is there a timing for the next release / can you cut one? We are having a hard time pulling the main branch to get [this commit ](https://github.com/contribsys/faktory_worker_ruby/commit/fdf75823c79c50f1e8f07544f292d8d82db1a77f)and having it boot correctly in our k8s cluster. We would rather not rewrite our config just to change it back when the release comes.

**Comment by mperham** [comment]
Sure, I just released 2.0.0.

**Comment by Deekor** [comment]
Thanks!
