### ISSUE TITLE
Fetch information about jobs in the retry or dead set?

### ISSUE THREAD

**Issue by BigBlue79** [contribsys/faktory_worker_ruby#88]
We have a large-ish backlog of dead jobs, and we're looking to optimize which ones to retry. To do so, we need to look at the args of the jobs in the dead set and compare them to some state stored in a database.

Is there a way to fetch information (eg: the args) from the jobs in the retry set or dead set using the ruby client? I see some elements that look like they could work in the `Mutate` module, but that looks like it's for... well, mutating those jobs. 

There's obviously _some_ way to fetch those jobs (since they're visible in the Web UI), but is that way to available to the ruby client?

**Comment by BigBlue79** [comment]
Sounds good - we actually made the same exact same json-endpoint addition you're describing in-house for our Sidekiq queues, so you have one vote in favour of that design choice 👍

**Comment by mperham** [comment]
I started implementing something yesterday and stopped when I realized I was just reinventing Redis's ZSCAN and ZRANGE commands. I think you can get a long way with just `redis-cli -s <path-to-data-location-from-/debug>`:

```
% redis-cli -s /Users/mperham/.faktory/db/redis.sock
redis /Users/mperham/.faktory/db/redis.sock> keys *
  1) "failures:2024-08-24"
  2) "failures:2024-06-26"
redis /Users/mperham/.faktory/db/redis.sock> type default
list
redis /Users/mperham/.faktory/db/redis.sock> zrange retries 0 1 withscores
1) "{\"jid\":\"a9d249ae2f856bf9\",\"queue\":\"bulk\",\"jobtype\":\"Failer\",\"args\":[1,2,3,\"\\r\\n\"],\"created_at\":\"2024-10-30T15:36:25.444535Z\",\"enqueued_at\":\"2024-10-30T15:37:05.937156Z\",\"retry\":5,\"failure\":{\"retry_count\":1,\"remaining\":4,\"failed_at\":\"2024-10-30T15:36:25.458658Z\",\"next_at\":\"2024-10-30T15:37:53.939234Z\",\"message\":\"oops\",\"errtype\":\"RuntimeError\",\"backtrace\":[\"/Users/mperham/src/github.com/contribsys/faktory/test/ruby/app.rb:19:in `perform'\",\"/Users/mperham/src/fwr/lib/faktory/processor.rb:146:in `block (2 levels) in process'\",\"/Users/mperham/src/fwr/lib/faktory/middleware/chain.rb:129:in `block in invoke'\",\"/Users/mperham/src/fwr/lib/faktory/middleware/batch.rb:21:in `call'\",\"/Users/mperham/src/fwr/lib/faktory/middleware/chain.rb:131:in `block in invoke'\",\"/Users/mperham/src/fwr/lib/faktory/middleware/chain.rb:134:in `invoke'\",\"/Users/mperham/src/fwr/lib/faktory/processor.rb:145:in `block in process'\",\"/Users/mperham/src/fwr/lib/faktory/processor.rb:135:in `block (3 levels) in dispatch'\",\"/Users/mperham/src/fwr/lib/faktory.rb:33:in `block in \\u003cmodule:Faktory\\u003e'\",\"/Users/mperham/src/fwr/lib/faktory/processor.rb:130:in `block (2 levels) in dispatch'\",\"/Users/mperham/src/fwr/lib/faktory/job_logger.rb:6:in `call'\",\"/Users/mperham/src/fwr/lib/faktory/processor.rb:125:in `block in dispatch'\",\"/Users/mperham/src/fwr/lib/faktory/logging.rb:43:in `with_context'\",\"/Users/mperham/src/fwr/lib/faktory/logging.rb:37:in `with_job_hash_context'\",\"/Users/mperham/src/fwr/lib/faktory/processor.rb:124:in `dispatch'\",\"/Users/mperham/src/fwr/lib/faktory/processor.rb:144:in `process'\",\"/Users/mperham/src/fwr/lib/faktory/processor.rb:88:in `process_one'\",\"/Users/mperham/src/fwr/lib/faktory/processor.rb:71:in `run'\",\"/Users/mperham/src/fwr/lib/faktory/util.rb:17:in `watchdog'\",\"/Users/mperham/src/fwr/lib/faktory/util.rb:26:in `block in safe_thread'\"]}}"
2) "1730302673.939234"
```

**Comment by rocktavious** [comment]
@mperham - We don't use an external redis for Faktory we just use the built in one.  It looks like the container doesn't have `redis-cli` in it

```
> k exec -it opslevel-faktory-0 -- /bin/sh
Defaulted container "config-watcher" out of: config-watcher, server
> redis-cli -h
/bin/sh: redis-cli: not found
```

If we add the `redis-cli` to the image would you expect that we can still connect over the `.sock` file.  Does the built in redis for faktory server ent use redis over the `.sock` file?

**Comment by mperham** [comment]
I believe so. Can you expose the sock outside of the container? I only add the bare minimum to the container necessary for runtime functionality to keep down image size.

**Comment by rocktavious** [comment]
Ya I'll take a look not something i'm familiar with doing (exposing the .sock file to other containers in a pod)

**Comment by mperham** [comment]
You can also use an external Redis running in another container with redis-cli in it but that’s a larger network architecture change.

**Comment by rocktavious** [comment]
@mperham it looks like the sock location is based on the persistent directory location.

https://github.com/contribsys/faktory/blob/main/cli/cli.go#L46
https://github.com/contribsys/faktory/blob/main/cli/cli.go#L152

To expose the sock to another container in the pod i need to mount a shared volume between the pods which means i need to move the persistent directory location.  This is not something i can really do to a running faktory instance serving our production workloads.

**Comment by mperham** [comment]
It's reasonable to ship redis-cli in the image. I think about that. Sorry for the trouble, I wish I had an easy solution.

**Comment by mperham** [comment]
This blog post seems to indicate that a redis-cli binary is packaged with the `redis` package in Alpine Linux. Could you verify you are using a recent Faktory version and a stock image?

**Comment by mperham** [comment]
Oops, https://devcoops.com/install-redis-cli-on-alpine-linux/

**Comment by rocktavious** [comment]
The container i exec'd into was running
```
Image:         docker.contribsys.com/contribsys/faktory-ent:1.8.0
```

I upgraded our staging environment to
```
Image:         docker.contribsys.com/contribsys/faktory-ent:1.9.0
```

and exec'd into it and got this

```
/ # redis-cli -v
/bin/sh: redis-cli: not found
```

Additionally because the container is so trimmed down it appears there is no `sudo` or `apk`

```
/ # sudo apk update
/bin/sh: sudo: not found
/ # apk update
/bin/sh: apk: not found
```

**Comment by mperham** [comment]
Can you show me how you got a shell in the image? I want to make sure I can test your way to verify any fix I make.

**Comment by mperham** [comment]
Booyah!
